language: cpp

compiler:
  - clang
  - gcc

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

script:
  - cd travis
  - cmake ../
  - make
  - ./cpplzw random_byte_from_32_bytes_input.txt
  - cmp output random_byte_from_32_bytes_output.txt
  - ./cpplzw random_bytes_input.txt
  - cmp output random_bytes_output.txt
  - ./cpplzw repeating_byte_sequence_input.txt
  - cmp output repeating_byte_sequence_output.txt
  - ./cpplzw single_byte_repeat_input.txt
  - cmp output single_byte_repeat_output.txt
